version: '3.8' 

services:
  db:
    image: postgres:latest
    container_name: property_db
    environment:
      - POSTGRES_DB=property_db
      - POSTGRES_USER=property_user
      - POSTGRES_PASSWORD=property_pass
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432" 

  cache:
    image: redis:latest
    container_name: property_cache
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data 

volumes:
  postgres_data:
  redis_data: 